services: # docker-compose -f docker-compose.arm.yml down -v; docker compose -f docker-compose.arm.yml up --force-recreate --build
  ui:
    image: ghcr.io/yanhao98/orion-visor-ui:docker-arm
    build:
      context: .
      dockerfile: docker-arm/Dockerfile.ui
    ports:
      - ${UI_PORT:-80}:80
    depends_on:
      - service
  service:
    image: ghcr.io/yanhao98/orion-visor-service:docker-arm
    build:
      context: .
      dockerfile: docker-arm/Dockerfile.service
    ports:
      - ${SERVICE_PORT:-9200}:9200
    healthcheck:
      test: [ "CMD", "curl", "http://127.0.0.1:9200/orion-visor/api/server/bootstrap/health" ]
      interval: 15s
      timeout: 300s
      retries: 15
      start_period: 3s
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-orion_visor}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-Data@123456}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-Data@123456}
      - SECRET_KEY=${SECRET_KEY:-uQeacXV8b3isvKLK}
      - DEMO_MODE=${DEMO_MODE:-false}
  mysql:
    image: ghcr.io/yanhao98/orion-visor-mysql:docker-arm
    build:
      context: .
      dockerfile: docker-arm/Dockerfile.mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-orion_visor}
      - MYSQL_USER=${MYSQL_USER:-orion}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-Data@123456}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-Data@123456}
    # volumes:
    #   - ${VOLUME_BASE:-/data/orion-visor-space/docker-volumes}/mysql/var-lib-mysql:/var/lib/mysql
    #   - ${VOLUME_BASE:-/data/orion-visor-space/docker-volumes}/mysql/var-lib-mysql-files:/var/lib/mysql-files
    #   - ${VOLUME_BASE:-/data/orion-visor-space/docker-volumes}/mysql/etc-mysql:/etc/mysql
    healthcheck:
      test: [ "CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/3306" ]
      interval: 15s
      timeout: 60s
      retries: 15
      start_period: 3s
  redis:
    image: redis:latest
    ports:
      - 6380:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-Data@123456}
    # volumes:
    #   - ${VOLUME_BASE:-/data/orion-visor-space/docker-volumes}/redis/data:/data
    command: sh -c "exec redis-server --requirepass $${REDIS_PASSWORD}"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 60s
      retries: 15
      start_period: 3s